### ISSUE TITLE
Creare due costruttori su Chat

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/kezappj4j#2]
Creare costruttori con tutte le proprietà e senza nessuna.

**Comment by Andreadott00** [comment]
fatto

**Comment by luca-lezzerini** [comment]
Manca l'indicazione del commit!!!!!!

**Comment by Andreadott00** [comment]
risolto Commit->ba7dd221e268be5a0b86acdc22238678ccf2b0d7

**Comment by luca-lezzerini** [comment]
ba7dd221e268be5a0b86acdc22238678ccf2b0d7
