### ISSUE TITLE
Costruttori vicini

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/kezappj4j#3]
I costruttori devono essere tutti contigui e non separati da metodi

**Comment by AnaKovacevicChisena** [comment]
Risolto

**Comment by luca-lezzerini** [comment]
Manca l'indicazione del commit!!!!!!

**Comment by luca-lezzerini** [comment]
Risolto commit f17a73d0e8d01c8dddee1d1ef43327d28dd3fac6
